/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as ImagesRouteImport } from './routes/images'
import { Route as WriterRouteImport } from './routes/writer'
import { Route as ResearchIndexRouteImport } from './routes/research.index'
import { Route as ResearchProjectIdRouteImport } from './routes/research_.$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesRoute = ImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => rootRouteImport,
} as any)
const WriterRoute = WriterRouteImport.update({
  id: '/writer',
  path: '/writer',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchIndexRoute = ResearchIndexRouteImport.update({
  id: '/research/',
  path: '/research/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchProjectIdRoute = ResearchProjectIdRouteImport.update({
  id: '/research_/$projectId',
  path: '/research/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/documents': typeof DocumentsRoute
  '/images': typeof ImagesRoute
  '/writer': typeof WriterRoute
  '/research/$projectId': typeof ResearchProjectIdRoute
  '/research/': typeof ResearchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/documents': typeof DocumentsRoute
  '/images': typeof ImagesRoute
  '/writer': typeof WriterRoute
  '/research/$projectId': typeof ResearchProjectIdRoute
  '/research': typeof ResearchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/documents': typeof DocumentsRoute
  '/images': typeof ImagesRoute
  '/writer': typeof WriterRoute
  '/research_/$projectId': typeof ResearchProjectIdRoute
  '/research/': typeof ResearchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/documents'
    | '/images'
    | '/writer'
    | '/research/$projectId'
    | '/research/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/documents'
    | '/images'
    | '/writer'
    | '/research/$projectId'
    | '/research'
  id:
    | '__root__'
    | '/'
    | '/documents'
    | '/images'
    | '/writer'
    | '/research_/$projectId'
    | '/research/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocumentsRoute: typeof DocumentsRoute
  ImagesRoute: typeof ImagesRoute
  WriterRoute: typeof WriterRoute
  ResearchProjectIdRoute: typeof ResearchProjectIdRoute
  ResearchIndexRoute: typeof ResearchIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images': {
      id: '/images'
      path: '/images'
      fullPath: '/images'
      preLoaderRoute: typeof ImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writer': {
      id: '/writer'
      path: '/writer'
      fullPath: '/writer'
      preLoaderRoute: typeof WriterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/': {
      id: '/research/'
      path: '/research'
      fullPath: '/research/'
      preLoaderRoute: typeof ResearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research_/$projectId': {
      id: '/research_/$projectId'
      path: '/research/$projectId'
      fullPath: '/research/$projectId'
      preLoaderRoute: typeof ResearchProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocumentsRoute: DocumentsRoute,
  ImagesRoute: ImagesRoute,
  WriterRoute: WriterRoute,
  ResearchProjectIdRoute: ResearchProjectIdRoute,
  ResearchIndexRoute: ResearchIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
