/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as ImagesRouteImport } from './routes/images'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as WriterRouteImport } from './routes/writer'
import { Route as ResearchProjectIdRouteImport } from './routes/research.$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesRoute = ImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const WriterRoute = WriterRouteImport.update({
  id: '/writer',
  path: '/writer',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchProjectIdRoute = ResearchProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ResearchRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/documents': typeof DocumentsRoute
  '/images': typeof ImagesRoute
  '/research': typeof ResearchRouteWithChildren
  '/writer': typeof WriterRoute
  '/research/$projectId': typeof ResearchProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/documents': typeof DocumentsRoute
  '/images': typeof ImagesRoute
  '/research': typeof ResearchRouteWithChildren
  '/writer': typeof WriterRoute
  '/research/$projectId': typeof ResearchProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/documents': typeof DocumentsRoute
  '/images': typeof ImagesRoute
  '/research': typeof ResearchRouteWithChildren
  '/writer': typeof WriterRoute
  '/research/$projectId': typeof ResearchProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/documents'
    | '/images'
    | '/research'
    | '/writer'
    | '/research/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/documents'
    | '/images'
    | '/research'
    | '/writer'
    | '/research/$projectId'
  id:
    | '__root__'
    | '/'
    | '/documents'
    | '/images'
    | '/research'
    | '/writer'
    | '/research/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocumentsRoute: typeof DocumentsRoute
  ImagesRoute: typeof ImagesRoute
  ResearchRoute: typeof ResearchRouteWithChildren
  WriterRoute: typeof WriterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images': {
      id: '/images'
      path: '/images'
      fullPath: '/images'
      preLoaderRoute: typeof ImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writer': {
      id: '/writer'
      path: '/writer'
      fullPath: '/writer'
      preLoaderRoute: typeof WriterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/$projectId': {
      id: '/research/$projectId'
      path: '/$projectId'
      fullPath: '/research/$projectId'
      preLoaderRoute: typeof ResearchProjectIdRouteImport
      parentRoute: typeof ResearchRoute
    }
  }
}

interface ResearchRouteChildren {
  ResearchProjectIdRoute: typeof ResearchProjectIdRoute
}

const ResearchRouteChildren: ResearchRouteChildren = {
  ResearchProjectIdRoute: ResearchProjectIdRoute,
}

const ResearchRouteWithChildren = ResearchRoute._addFileChildren(
  ResearchRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocumentsRoute: DocumentsRoute,
  ImagesRoute: ImagesRoute,
  ResearchRoute: ResearchRouteWithChildren,
  WriterRoute: WriterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
